TARGET = mating_one-point-crossover
BINDIR = ../../bin/modules
OBJDIR = ../../build/unix

CPP = icpc
CFLAGS = -xHost -fast -Wall -I ../../include -fPIC

default: $(TARGET).so

$(OBJDIR)/Random.o:
	$(CPP) -c ../../src/Random.cpp $(CFLAGS) -o $@

$(OBJDIR)/%.o: %.cpp
	$(CPP) -c $< $(CFLAGS) -o $@

$(TARGET).so: $(OBJDIR)/Random.o $(OBJDIR)/$(TARGET).o
	$(CPP) -shared -static-intel -o $(BINDIR)/$@ $^

clean:
	rm -f $(OBJDIR)/$(TARGET).o
