Ngene: /media/Junkbox/Projects/Ngene/src/Ngene.cpp File Reference
/media/Junkbox/Projects/Ngene/src/Ngene.cpp File Reference
#include "Ngene.h"
Namespaces
namespace std
Functions
int main ()
Variables
const char * NGENE_VERSION = "0.2007.10.17"
Function Documentation
int main ()
Definition at line 9 of file Ngene.cpp.
References Configuration::adult_pool_capacity, Specimen::age, SettingsManager::config, Configuration::doomsday, Configuration::elitism, Specimen::fitness, PluginManager::fitness_assess, Specimen::genotype, PluginManager::genotype_to_str, SettingsManager::is_loaded(), Configuration::lifespan, Logger::log(), PluginManager::mate, Configuration::mating_rate, Configuration::max_prodigies, PluginManager::modules, PluginManager::mutate, Configuration::mutation_rate, NGENE_VERSION, offspring(), PluginManager::offspring_rate, Configuration::offspring_rate, PluginManager::seed, and PluginManager::select.
Variable Documentation
const char* NGENE_VERSION = "0.2007.10.17"
Definition at line 7 of file Ngene.cpp.
Referenced by main().